name: Flake8 Code Quality Check

on:
  push:
    branches:
      - dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install flake8
    - name: Run flake8
      run: flake8 .